"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

def findTheDifference(s:'str', t: 'str') -> 'str':

    s = sum([ord(i) for i in s])
    t = sum([ord(i) for i in t])

    return chr(t-s)

print(findTheDifference('abcd', 'abcde'), '\nShould be e')
print(findTheDifference('wxyz', 'awxyz'), '\nShould be a')